!                   *******************
                    SUBROUTINE DEALMESH
!                   *******************
     &(MESH)
!
!***********************************************************************
! BIEF   V7P1
!***********************************************************************
!
!brief    Deallocates a bief_mesh mesh structure.
!
!history  Y. AUDOUIN (EDF LAB, LNHE)
!+        23/05/2013
!+        V6P3
!+   First version.
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!| MESH           |<->| MESH STRUCTURE TO BE ALLOCATED
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF, EX_DEALMESH => DEALMESH
!
      USE DECLARATIONS_TELEMAC
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!
      TYPE(BIEF_MESH)  , INTENT(INOUT)           :: MESH
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!
      DEALLOCATE(MESH%NDS)
      CALL BIEF_DEALLOBJ(MESH%XEL)
      DEALLOCATE(MESH%XEL)
      CALL BIEF_DEALLOBJ(MESH%YEL)
      DEALLOCATE(MESH%YEL)
      CALL BIEF_DEALLOBJ(MESH%ZEL)
      DEALLOCATE(MESH%ZEL)
      CALL BIEF_DEALLOBJ(MESH%SURFAC)
      DEALLOCATE(MESH%SURFAC)
      CALL BIEF_DEALLOBJ(MESH%SURDET)
      DEALLOCATE(MESH%SURDET)
      CALL BIEF_DEALLOBJ(MESH%LGSEG)
      DEALLOCATE(MESH%LGSEG)
      CALL BIEF_DEALLOBJ(MESH%XSGBOR)
      DEALLOCATE(MESH%XSGBOR)
      CALL BIEF_DEALLOBJ(MESH%YSGBOR)
      DEALLOCATE(MESH%YSGBOR)
      CALL BIEF_DEALLOBJ(MESH%ZSGBOR)
      DEALLOCATE(MESH%ZSGBOR)
      CALL BIEF_DEALLOBJ(MESH%XNEBOR)
      DEALLOCATE(MESH%XNEBOR)
      CALL BIEF_DEALLOBJ(MESH%YNEBOR)
      DEALLOCATE(MESH%YNEBOR)
      CALL BIEF_DEALLOBJ(MESH%ZNEBOR)
      DEALLOCATE(MESH%ZNEBOR)
      CALL BIEF_DEALLOBJ(MESH%X)
      DEALLOCATE(MESH%X)
      MESH%X => NULL()
      CALL BIEF_DEALLOBJ(MESH%Y)
      DEALLOCATE(MESH%Y)
      CALL BIEF_DEALLOBJ(MESH%Z)
      DEALLOCATE(MESH%Z)
      CALL BIEF_DEALLOBJ(MESH%COSLAT)
      DEALLOCATE(MESH%COSLAT)
      CALL BIEF_DEALLOBJ(MESH%SINLAT)
      DEALLOCATE(MESH%SINLAT)
      CALL BIEF_DEALLOBJ(MESH%DISBOR)
      DEALLOCATE(MESH%DISBOR)
      CALL BIEF_DEALLOBJ(MESH%M)
      DEALLOCATE(MESH%M)
      CALL BIEF_DEALLOBJ(MESH%MSEG)
      DEALLOCATE(MESH%MSEG)
      CALL BIEF_DEALLOBJ(MESH%W)
      DEALLOCATE(MESH%W)
      CALL BIEF_DEALLOBJ(MESH%T)
      DEALLOCATE(MESH%T)
      CALL BIEF_DEALLOBJ(MESH%VNOIN)
      DEALLOCATE(MESH%VNOIN)
      CALL BIEF_DEALLOBJ(MESH%CMI)
      DEALLOCATE(MESH%CMI)
      CALL BIEF_DEALLOBJ(MESH%AIRST)
      DEALLOCATE(MESH%AIRST)
      CALL BIEF_DEALLOBJ(MESH%DTHAUT)
      DEALLOCATE(MESH%DTHAUT)
      CALL BIEF_DEALLOBJ(MESH%DPX)
      DEALLOCATE(MESH%DPX)
      CALL BIEF_DEALLOBJ(MESH%DPY)
      DEALLOCATE(MESH%DPY)
      CALL BIEF_DEALLOBJ(MESH%COORDG)
      DEALLOCATE(MESH%COORDG)
      CALL BIEF_DEALLOBJ(MESH%COORDS)
      DEALLOCATE(MESH%COORDS)
      CALL BIEF_DEALLOBJ(MESH%COORDR)
      DEALLOCATE(MESH%COORDR)
      CALL BIEF_DEALLOBJ(MESH%XSEG)
      DEALLOCATE(MESH%XSEG)
      CALL BIEF_DEALLOBJ(MESH%YSEG)
      DEALLOCATE(MESH%YSEG)
      CALL BIEF_DEALLOBJ(MESH%IFAC)
      DEALLOCATE(MESH%IFAC)
      DEALLOCATE(MESH%NELEM)
      DEALLOCATE(MESH%NELMAX)
      DEALLOCATE(MESH%NPTFR)
      DEALLOCATE(MESH%NPTFRX)
      DEALLOCATE(MESH%NELEB)
      DEALLOCATE(MESH%NELEBX)
      DEALLOCATE(MESH%DIM1)
      DEALLOCATE(MESH%TYPELM)
      DEALLOCATE(MESH%TYPELMBND)
      DEALLOCATE(MESH%NPOIN)
      DEALLOCATE(MESH%NPMAX)
      DEALLOCATE(MESH%MXPTVS)
      DEALLOCATE(MESH%MXELVS)
      DEALLOCATE(MESH%LV)
      DEALLOCATE(MESH%NSEG)
      CALL BIEF_DEALLOBJ(MESH%IKLE)
      DEALLOCATE(MESH%IKLE)
      CALL BIEF_DEALLOBJ(MESH%KLEI)
      DEALLOCATE(MESH%KLEI)
      CALL BIEF_DEALLOBJ(MESH%IFABOR)
      DEALLOCATE(MESH%IFABOR)
      CALL BIEF_DEALLOBJ(MESH%NELBOR)
      DEALLOCATE(MESH%NELBOR)
      CALL BIEF_DEALLOBJ(MESH%NULONE)
      DEALLOCATE(MESH%NULONE)
      CALL BIEF_DEALLOBJ(MESH%KP1BOR)
      DEALLOCATE(MESH%KP1BOR)
      CALL BIEF_DEALLOBJ(MESH%NBOR)
      DEALLOCATE(MESH%NBOR)
      CALL BIEF_DEALLOBJ(MESH%IKLBOR)
      DEALLOCATE(MESH%IKLBOR)
      CALL BIEF_DEALLOBJ(MESH%IKLEM1)
      DEALLOCATE(MESH%IKLEM1)
      CALL BIEF_DEALLOBJ(MESH%LIMVOI)
      DEALLOCATE(MESH%LIMVOI)
      CALL BIEF_DEALLOBJ(MESH%IFANUM)
      DEALLOCATE(MESH%IFANUM)
      CALL BIEF_DEALLOBJ(MESH%GLOSEG)
      DEALLOCATE(MESH%GLOSEG)
      CALL BIEF_DEALLOBJ(MESH%ELTSEG)
      DEALLOCATE(MESH%ELTSEG)
      CALL BIEF_DEALLOBJ(MESH%ORISEG)
      DEALLOCATE(MESH%ORISEG)
      CALL BIEF_DEALLOBJ(MESH%GLOSEGBOR)
      DEALLOCATE(MESH%GLOSEGBOR)
      CALL BIEF_DEALLOBJ(MESH%ELTSEGBOR)
      DEALLOCATE(MESH%ELTSEGBOR)
      CALL BIEF_DEALLOBJ(MESH%ORISEGBOR)
      DEALLOCATE(MESH%ORISEGBOR)
      CALL BIEF_DEALLOBJ(MESH%ELTCAR)
      DEALLOCATE(MESH%ELTCAR)
      CALL BIEF_DEALLOBJ(MESH%KNOLG)
      DEALLOCATE(MESH%KNOLG)
      CALL BIEF_DEALLOBJ(MESH%NACHB)
      DEALLOCATE(MESH%NACHB)
      CALL BIEF_DEALLOBJ(MESH%ISEG)
      DEALLOCATE(MESH%ISEG)
      CALL BIEF_DEALLOBJ(MESH%INDPU)
      DEALLOCATE(MESH%INDPU)
      CALL BIEF_DEALLOBJ(MESH%NHP)
      DEALLOCATE(MESH%NHP)
      CALL BIEF_DEALLOBJ(MESH%NHM)
      DEALLOCATE(MESH%NHM)
      CALL BIEF_DEALLOBJ(MESH%IFAPAR)
      DEALLOCATE(MESH%IFAPAR)
      DEALLOCATE(MESH%NB_NEIGHB)
      DEALLOCATE(MESH%NB_NEIGHB_SEG)
      CALL BIEF_DEALLOBJ(MESH%NB_NEIGHB_PT)
      CALL BIEF_DEALLOBJ(MESH%LIST_SEND)
      CALL BIEF_DEALLOBJ(MESH%NH_COM)
      CALL BIEF_DEALLOBJ(MESH%NB_NEIGHB_PT_SEG)
      CALL BIEF_DEALLOBJ(MESH%LIST_SEND_SEG)
      CALL BIEF_DEALLOBJ(MESH%NH_COM_SEG)
      IF(NCSIZE.GT.1) THEN
        IF(ASSOCIATED(MESH%BUF_SEND%I)) THEN
          DEALLOCATE(MESH%BUF_SEND%I)
          DEALLOCATE(MESH%BUF_RECV%I)
          IF(MODASS.EQ.2) THEN
            DEALLOCATE(MESH%BUF_SENDI8)
            DEALLOCATE(MESH%BUF_RECVI8)
          ENDIF
        ENDIF
      ENDIF
      CALL BIEF_DEALLOBJ(MESH%BUF_SEND)
      CALL BIEF_DEALLOBJ(MESH%BUF_RECV)
      IF (MODASS.EQ.3) THEN
        CALL BIEF_DEALLOBJ(MESH%BUF_SEND_ERR)
        CALL BIEF_DEALLOBJ(MESH%BUF_RECV_ERR)
      ENDIF
      IF(MODASS.EQ.2) THEN
        IF(ASSOCIATED(MESH%WI8)) DEALLOCATE(MESH%WI8)
        IF(ASSOCIATED(MESH%TI8)) DEALLOCATE(MESH%TI8)
      ENDIF
      DEALLOCATE(MESH%NB_NEIGHB_PT)
      DEALLOCATE(MESH%LIST_SEND)
      DEALLOCATE(MESH%NH_COM)
      DEALLOCATE(MESH%NB_NEIGHB_PT_SEG)
      DEALLOCATE(MESH%LIST_SEND_SEG)
      DEALLOCATE(MESH%NH_COM_SEG)
      DEALLOCATE(MESH%BUF_SEND)
      DEALLOCATE(MESH%BUF_RECV)
!
      CALL BIEF_DEALLOBJ(MESH%NUBO)
      DEALLOCATE(MESH%NUBO)
      CALL BIEF_DEALLOBJ(MESH%JMI)
      DEALLOCATE(MESH%JMI)
!
!-----------------------------------------------------------------------
!
      RETURN
      END SUBROUTINE DEALMESH
