
git clone https://gitlab.onelab.info/gmsh/gmsh.git

cd gmsh
git checkout tags/gmsh_4_11_1
GMSH_SRC=$PWD
cd ..

GMSH_INSTALL=$PWD

mkdir gmsh_building
cd gmsh_building

$gmsh_building_path=$PWD

cmake   -S $GMSH_SRC \
		-B . \
        -DCMAKE_BUILD_TYPE:STRING=Release \
        -DCMAKE_INSTALL_PREFIX=$GMSH_INSTALL \
        -DENABLE_3M:BOOL=OFF \
        -DENABLE_ALGLIB:BOOL=OFF \
        -DENABLE_ANN:BOOL=OFF \
        -DENABLE_BAMG:BOOL=ON \
        -DENABLE_BLAS_LAPACK:BOOL=OFF \
        -DENABLE_BLOSSOM:BOOL=OFF \
        -DENABLE_BUILD_ANDROID:BOOL=OFF \
        -DENABLE_BUILD_DYNAMIC:BOOL=ON \
        -DENABLE_BUILD_IOS:BOOL=OFF \
        -DENABLE_BUILD_LIB:BOOL=OFF \
        -DENABLE_BUILD_SHARED:BOOL=OFF \
        -DENABLE_CAIRO:BOOL=OFF \
        -DENABLE_CGNS:BOOL=OFF \
        -DENABLE_CGNS_CPEX0045:BOOL=OFF \
        -DENABLE_DINTEGRATION:BOOL=OFF \
        -DENABLE_DOMHEX:BOOL=OFF \
        -DENABLE_EIGEN:BOOL=ON \
        -DENABLE_FLTK:BOOL=OFF \
        -DENABLE_GEOMETRYCENTRAL:BOOL=OFF \
        -DENABLE_GETDP:BOOL=OFF \
        -DENABLE_GMM:BOOL=OFF \
        -DENABLE_GMP:BOOL=OFF \
        -DENABLE_GRAPHICS:BOOL=OFF \
        -DENABLE_HXT:BOOL=OFF \
        -DENABLE_KBIPACK:BOOL=OFF \
        -DENABLE_MATHEX:BOOL=OFF \
        -DENABLE_MED:BOOL=OFF \
        -DENABLE_MESH:BOOL=ON \
        -DENABLE_METIS:BOOL=OFF \
        -DENABLE_MMG:BOOL=OFF \
        -DENABLE_MPEG_ENCODE:BOOL=OFF \
        -DENABLE_MPI:BOOL=OFF \
        -DENABLE_MSVC_STATIC_RUNTIME:BOOL=OFF \
        -DENABLE_MUMPS:BOOL=OFF \
        -DENABLE_NCURSES:BOOL=OFF \
        -DENABLE_NETGEN:BOOL=OFF \
        -DENABLE_NUMPY:BOOL=OFF \
        -DENABLE_OCC:BOOL=OFF \
        -DENABLE_OCC_CAF:BOOL=OFF \
        -DENABLE_OCC_STATIC:BOOL=OFF \
        -DENABLE_OCC_TBB:BOOL=OFF \
        -DENABLE_ONELAB:BOOL=OFF \
        -DENABLE_ONELAB_METAMODEL:BOOL=OFF \
        -DENABLE_OPENACC:BOOL=OFF \
        -DENABLE_OPENMP:BOOL=OFF \
        -DENABLE_OPTHOM:BOOL=OFF \
        -DENABLE_OSMESA:BOOL=OFF \
        -DENABLE_OS_SPECIFIC_INSTALL:BOOL=OFF \
        -DENABLE_P4EST:BOOL=OFF \
        -DENABLE_PACKAGE_STRIP:BOOL=OFF \
        -DENABLE_PARSER:BOOL=OFF \
        -DENABLE_PETSC:BOOL=OFF \
        -DENABLE_PETSC4PY:BOOL=OFF \
        -DENABLE_PLUGINS:BOOL=OFF \
        -DENABLE_POPPLER:BOOL=OFF \
        -DENABLE_POST:BOOL=OFF \
        -DENABLE_PRIVATE_API:BOOL=OFF \
        -DENABLE_PRO:BOOL=OFF \
        -DENABLE_PROFILE:BOOL=OFF \
        -DENABLE_QUADMESHINGTOOLS:BOOL=OFF \
        -DENABLE_QUADTRI:BOOL=OFF \
        -DENABLE_REVOROPT:BOOL=OFF \
        -DENABLE_RPATH:BOOL=OFF \
        -DENABLE_SLEPC:BOOL=OFF \
        -DENABLE_SOLVER:BOOL=OFF \
        -DENABLE_SYSTEM_CONTRIB:BOOL=OFF \
        -DENABLE_TCMALLOC:BOOL=OFF \
        -DENABLE_TESTS:BOOL=OFF \
        -DENABLE_TOUCHBAR:BOOL=OFF \
        -DENABLE_VISUDEV:BOOL=OFF \
        -DENABLE_VOROPP:BOOL=OFF \
        -DENABLE_WINSLOWUNTANGLER:BOOL=OFF \
        -DENABLE_WRAP_JAVA:BOOL=OFF \
        -DENABLE_WRAP_PYTHON:BOOL=OFF \
        -DENABLE_ZIPPER:BOOL=OFF
        
cmake --build .  --config Release -j20
cmake --install .


rm -r $gmsh_building_path
rm -r $GMSH_SRC
