FROM reos_dependencies
LABEL maintainer="vcloarec@gmail.com"

RUN mkdir reos
COPY build_reos.sh /reos/
RUN chmod +x /reos/build_reos.sh

RUN export QGIS_INSTALL=/qgis \
       && export QGIS_APP_SRC=/qgis/app_src \
       && export MDAL_INSTALL=/mdal \
       && export GMSH_INSTALL=/gmsh \
       && export HEC_DSS_INSTALL=/hecdss \
       && cd reos && ./build_reos.sh

