INCLUDEPATH+=$${BOOST_ROOT_PATH}
INCLUDEPATH+=$${CGAL_INCLUDE_PATH}

win32{
    LIBS += $${CGAL_LIB_RELEASE_MSVC}
} else {
    LIBS += -L$${CGAL_LIB_RELEASE_PATH} -lCGAL
}

LIBS += -L$${CGAL_LIB_RELEASE_PATH} -lgmp

