      SUBROUTINE AD_GAIA_TIMESTEP_END

        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_GAIA_TIMESTEP_END [lib]'

      END SUBROUTINE AD_GAIA_TIMESTEP_END
