      SUBROUTINE AD_GAIA_MAIN_AFTER_LECDON_GAIA

        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0)
!     &      WRITE(LU,*) 'AD_GAIA_MAIN_AFTER_LECDON_GAIA [lib]'

      END SUBROUTINE AD_GAIA_MAIN_AFTER_LECDON_GAIA
