      SUBROUTINE AD_SISYPHE_TIMESTEP_BEGIN

        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_SISYPHE_TIMESTEP_BEGIN [lib]'

      END SUBROUTINE AD_SISYPHE_TIMESTEP_BEGIN
