      SUBROUTINE AD_SISYPHE_END

        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_SISYPHE_END [lib]'

      END SUBROUTINE AD_SISYPHE_END
