      SUBROUTINE AD_SISYPHE_MAIN_AFTER_LECDON_SISYPHE

        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0)
!     &      WRITE(LU,*) 'AD_SISYPHE_MAIN_AFTER_LECDON_SISYPHE [lib]'

      END SUBROUTINE AD_SISYPHE_MAIN_AFTER_LECDON_SISYPHE
