      SUBROUTINE AD_TOMAWAC_INITIALISATION_END

        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0)
!     &      WRITE(LU,*) 'AD_TOMAWAC_INITIALISATION_END [lib]'

      END SUBROUTINE AD_TOMAWAC_INITIALISATION_END
