      SUBROUTINE AD_TELEMAC3D_MAIN_AFTER_LECDON_GAIA
        USE DECLARATIONS_SPECIAL
        
        IMPLICIT NONE

        
!!        IF(DEBUG.GT.0) THEN
!!           WRITE(LU,*) 'AD_TELEMAC3D_MAIN_AFTER_LECDON_GAIA [lib]'
!!        END IF

      END SUBROUTINE AD_TELEMAC3D_MAIN_AFTER_LECDON_GAIA
