      SUBROUTINE AD_TELEMAC3D_TIMESTEP_BEGIN
  
        USE DECLARATIONS_SPECIAL
        
        IMPLICIT NONE

        
!!        WRITE(LU,*) 'AD_TELEMAC3D_TIMESTEP_BEGIN [lib]'
!!        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_TELEMAC3D_TIMESTEP_BEGIN [lib]'

      END SUBROUTINE AD_TELEMAC3D_TIMESTEP_BEGIN
