      SUBROUTINE AD_TELEMAC3D_MAIN_AFTER_LECDON_TELEMAC3D
        USE DECLARATIONS_SPECIAL
        
        IMPLICIT NONE

        
!!        WRITE(LU,*) 'AD_TELEMAC3D_MAIN_AFTER_LECDON_TELEMAC3D [lib]'
!!        IF(DEBUG.GT.0) THEN
!!           WRITE(LU,*) 'AD_TELEMAC3D_MAIN_AFTER_LECDON_TELEMAC3D [lib]'
!!        END IF

      END SUBROUTINE AD_TELEMAC3D_MAIN_AFTER_LECDON_TELEMAC3D
