      SUBROUTINE AD_TELEMAC3D_MAIN_FINALIZE
  
        USE DECLARATIONS_SPECIAL
        
        IMPLICIT NONE

        
!!        WRITE(LU,*) 'AD_TELEMAC3D_MAIN_FINALIZE [lib]'
!!        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_TELEMAC3D_MAIN_FINALIZE [lib]'

      END SUBROUTINE AD_TELEMAC3D_MAIN_FINALIZE
