      SUBROUTINE AD_TELEMAC3D_SUBITERATION_BEGIN

        USE DECLARATIONS_SPECIAL

        IMPLICIT NONE


!!        IF(DEBUG.GT.0)
!!     &      WRITE(LU,*) 'AD_TELEMAC3D_SUBITERATION_BEGIN [lib]'

      END SUBROUTINE AD_TELEMAC3D_SUBITERATION_BEGIN
