      SUBROUTINE AD_TOMAWAC_MAIN_AFTER_LECDON_TOMAWAC

        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0)
!     &     WRITE(LU,*) 'AD_TOMAWAC_MAIN_AFTER_LECDON_TOMAWAC [lib]'

      END SUBROUTINE AD_TOMAWAC_MAIN_AFTER_LECDON_TOMAWAC
