name: Build and Push Worker Docker image

on:
  push:
    branches:
      - main   # run when code is pushed to main
  workflow_dispatch: # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          BUILDKIT_PROGRESS: plain
        with:
          context: .
          file: worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reos_worker_env:latest